/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:47:28 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import Game.About;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class About_ESTest extends About_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      About about0 = new About();
  }
}
