/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:49:30 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Game.ChooseLevel;
import java.awt.Image;
import javax.swing.DebugGraphics;
import javax.swing.JButton;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChooseLevel_ESTest extends ChooseLevel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      JButton jButton0 = chooseLevel0.getRestartButton();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      JButton jButton0 = chooseLevel0.getHardLevel();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      JButton jButton0 = chooseLevel0.getResumeButton();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      int int0 = chooseLevel0.getId();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      JButton jButton0 = chooseLevel0.getEasyLevel();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      DebugGraphics debugGraphics0 = new DebugGraphics();
      // Undeclared exception!
      try { 
        chooseLevel0.paintComponent(debugGraphics0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.swing.DebugGraphics", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      chooseLevel0.setBackImage((Image) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      chooseLevel0.Choose2();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      chooseLevel0.Choose1();
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ChooseLevel chooseLevel0 = new ChooseLevel();
      JButton jButton0 = chooseLevel0.getMediumLevel();
  }
}
