/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:46:44 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import Game.GameElementPanel;
import Game.Mino;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GameElementPanel_ESTest extends GameElementPanel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GameElementPanel gameElementPanel0 = new GameElementPanel("", 70);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GameElementPanel gameElementPanel0 = new GameElementPanel("3z&E;*$jNcBf", 0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GameElementPanel gameElementPanel0 = new GameElementPanel((String) null, 1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Mino mino0 = new Mino((-516));
      GameElementPanel gameElementPanel0 = new GameElementPanel(mino0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GameElementPanel gameElementPanel0 = new GameElementPanel();
  }
}
