/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:49:21 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Game.GameOver;
import java.awt.Color;
import java.awt.Graphics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GameOver_ESTest extends GameOver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GameOver gameOver0 = new GameOver(148, 148, 662, 148, 1019, 1019, 662, (-2041), 662, 148);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GameOver gameOver0 = new GameOver((-1232), (-1678), 3906, 0, 1483, (-1678), 3906, (-1232), 3906, 9);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GameOver gameOver0 = new GameOver(4, 4, 4, 4, (-30), 879, 0, 2321, (-1), (-30));
      Color color0 = Color.RED;
      GameOver.ScoreTablePanel gameOver_ScoreTablePanel0 = gameOver0.new ScoreTablePanel(color0);
      // Undeclared exception!
      try { 
        gameOver_ScoreTablePanel0.paintComponent((Graphics) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Game.GameOver$ScoreTablePanel", e);
      }
  }
}
