/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:46:28 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import Game.Ghost;
import Game.Mino;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Ghost_ESTest extends Ghost_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mino mino0 = new Mino(4);
      Ghost ghost0 = new Ghost(mino0);
  }
}
