/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:48:57 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import Game.Help;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Help_ESTest extends Help_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Help help0 = new Help();
  }
}
