/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:48:39 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Game.HighScoreManager;
import Game.Score;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HighScoreManager_ESTest extends HighScoreManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager("");
      Vector<Score> vector0 = new Vector<Score>();
      Score score0 = new Score("", 0);
      boolean boolean0 = vector0.add(score0);
      // Undeclared exception!
      try { 
        highScoreManager0.setListe(vector0, score0, (-1746));
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 1
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager((-1379));
      Vector<Score> vector0 = new Vector<Score>();
      Score score0 = new Score("Game.Score", (-2425));
      boolean boolean0 = vector0.add(score0);
      Score score1 = new Score("+-'6^+", (-1379));
      // Undeclared exception!
      try { 
        highScoreManager0.setListe(vector0, score1, (-2425));
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 1
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager(0);
      // Undeclared exception!
      try { 
        highScoreManager0.updateScoreFile((Boolean) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Game.HighScoreManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager("");
      boolean boolean0 = FileSystemHandling.shouldAllThrowIOExceptions();
      highScoreManager0.updateScoreFile((Boolean) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager("");
      HighScoreManager highScoreManager1 = new HighScoreManager(0);
      Boolean boolean0 = Boolean.valueOf("Game.Score");
      highScoreManager0.updateScoreFile(boolean0);
      highScoreManager1.updateScoreFile(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager("");
      Boolean boolean0 = Boolean.TRUE;
      highScoreManager0.updateScoreFile(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager("Game.Score");
      Boolean boolean0 = Boolean.valueOf("");
      highScoreManager0.updateScoreFile(boolean0);
      // Undeclared exception!
      try { 
        highScoreManager0.loadScoreFile();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ObjectInputStream$PeekInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager("");
      Boolean boolean0 = Boolean.valueOf("^.`9R{6M|rAx");
      highScoreManager0.updateScoreFile(boolean0);
      highScoreManager0.loadScoreFile();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager(2564);
      // Undeclared exception!
      try { 
        highScoreManager0.getListe(2564);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ObjectInputStream$PeekInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      HighScoreManager highScoreManager0 = new HighScoreManager("");
      highScoreManager0.loadScoreFile();
  }
}
