/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:47:54 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Game.MatrixElement;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.SystemColor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MatrixElement_ESTest extends MatrixElement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Color color0 = Color.BLUE;
      MatrixElement matrixElement0 = new MatrixElement(color0, (Point) null);
      // Undeclared exception!
      try { 
        matrixElement0.draw((Graphics) null, (-1));
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Game.MatrixElement", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemColor systemColor0 = SystemColor.menuText;
      MatrixElement matrixElement0 = new MatrixElement(systemColor0, (Point) null);
      MatrixElement matrixElement1 = null;
      try {
        matrixElement1 = new MatrixElement(matrixElement0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Game.MatrixElement", e);
      }
  }
}
