/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:47:47 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Game.Option;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import javax.swing.DebugGraphics;
import javax.swing.JButton;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Option option0 = new Option();
      Object object0 = option0.getTreeLock();
      ActionEvent actionEvent0 = new ActionEvent(object0, 32767, "jieN)Z:q+.;3DO#qu");
      option0.actionPerformed(actionEvent0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Option option0 = new Option();
      DebugGraphics debugGraphics0 = new DebugGraphics();
      option0.draw(debugGraphics0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Option option0 = new Option();
      JButton jButton0 = option0.getHighScoreButton();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Option option0 = new Option();
      option0.efait();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Option option0 = new Option();
      // Undeclared exception!
      try { 
        option0.paintComponent((Graphics) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.swing.JComponent", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Option option0 = new Option();
      JButton jButton0 = option0.getUndecoratedButton();
  }
}
