/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:49:13 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Game.Timer;
import java.awt.Graphics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Timer_ESTest extends Timer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Timer timer0 = new Timer();
      timer0.update();
      timer0.update();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Timer timer0 = new Timer();
      // Undeclared exception!
      try { 
        timer0.paintComponent((Graphics) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.swing.JComponent", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Timer timer0 = new Timer();
      String string0 = timer0.toString();
  }
}
