/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:48:06 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Game.WindowLanch;
import java.awt.Graphics;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WindowLanch_ESTest extends WindowLanch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WindowLanch windowLanch0 = new WindowLanch(1144);
      WindowLanch.Exit windowLanch_Exit0 = null;
      try {
        windowLanch_Exit0 = windowLanch0.new Exit();
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WindowLanch windowLanch0 = new WindowLanch(550);
      // Undeclared exception!
      try { 
        windowLanch0.paintComponent((Graphics) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.swing.JComponent", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WindowLanch windowLanch0 = null;
      try {
        windowLanch0 = new WindowLanch();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Game.WindowLanch", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WindowLanch windowLanch0 = new WindowLanch((-2232));
      WindowLanch.Efait windowLanch_Efait0 = null;
      try {
        windowLanch_Efait0 = windowLanch0.new Efait((-2232), (JFrame) null);
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }
}
