/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jul 12 09:48:06 GMT 2024
 */

package Game;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class WindowLanch_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "Game.WindowLanch"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(WindowLanch_ESTest_scaffolding.class.getClassLoader() ,
      "Game.WindowLanch$Efait$1",
      "Game.Mino",
      "Game.StatsPanel",
      "Game.Ghost",
      "Game.GamePanel",
      "Game.GamePanel$KeyHandler",
      "Game.About",
      "Game.GameOver",
      "Game.MinoQueue",
      "Game.Score",
      "Game.WindowLanch$1",
      "Game.WindowLanch$Efait",
      "Game.Vue",
      "Game.GamePanel$Status",
      "Game.WindowLanch$4",
      "Game.WindowLanch$2",
      "Game.WindowLanch$3",
      "Game.WindowLanch",
      "Game.WindowLanch$Exit",
      "Game.Help",
      "Game.NavigationBar",
      "Game.GameOver$ScoreTablePanel",
      "Game.QueuePanel",
      "Game.WindowLanch$Exit$1",
      "Game.GamePanel$MatrixPanel",
      "Game.HighScoreManager",
      "Game.WindowLanch$Exit$3",
      "Game.ChooseLevel",
      "Game.WindowLanch$Exit$2",
      "Game.Option",
      "Game.HighScore"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(WindowLanch_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "Game.WindowLanch",
      "Game.WindowLanch$1",
      "Game.WindowLanch$2",
      "Game.WindowLanch$3",
      "Game.WindowLanch$4",
      "Game.WindowLanch$Efait",
      "Game.WindowLanch$Efait$1",
      "Game.WindowLanch$Exit",
      "Game.WindowLanch$Exit$1",
      "Game.WindowLanch$Exit$2",
      "Game.WindowLanch$Exit$3"
    );
  }
}
