/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 09:47:36 GMT 2024
 */

package Game;

import org.junit.Test;
import static org.junit.Assert.*;
import Game.Mino;
import Game.MinoQueue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MinoQueue_ESTest extends MinoQueue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MinoQueue minoQueue0 = new MinoQueue();
      Mino mino0 = minoQueue0.newMino();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MinoQueue minoQueue0 = new MinoQueue();
      minoQueue0.shiftUp();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MinoQueue minoQueue0 = new MinoQueue();
      Mino mino0 = minoQueue0.getHeld();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MinoQueue minoQueue0 = new MinoQueue();
      minoQueue0.setHeld((Mino) null);
  }
}
